export const fieldUnits = {
    'no2': 'g',
    'co2': 'g',
    'nox': 'g',
    'pmx': 'g',
    'hc': 'g',
    'co': 'g',
    'no2 mcg/m3': 'μg/m³',
    'fuel': 'g',
    'occupancy': 'cars/time slot',
    'speed': 'km/h',
    'time_window': 'hh:mm',
    'agricultural_landuse': 'm²',
    'commercial_landuse': 'm²',
    'industrial_landuse': 'm²',
    'natural_landuse': 'm²',
    'residential_landuse': 'm²',
    'food_pois': 'points',
    'fun_pois': 'points',
    'health_pois': 'points',
    'infrastructure_pois': 'points',
    'school_pois': 'points',
    'services_pois': 'points',
    'shop_pois': 'points',
    'sport_pois': 'points',
    'tourism_pois': 'points',
    'static_population': 'people',
};