services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8082:8080"
#    command: tail -F /dev/null
    volumes:
      - keycloak_data:/opt/keycloak/data
#      - ./export:/opt/keycloak/data/export
volumes:
  keycloak_data: