apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-ingress-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "ingress-pass"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "ingress-pass-read"
          serviceAccountRef:
            name: "default"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ingress-pass-secret
spec:
  dataFrom:
  - extract:
      key: ingress-pass-secret
      conversionStrategy: Default
  refreshInterval: 24h
  secretStoreRef:
    kind: SecretStore
    name: vault-ingress-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: basic-auth-desp
    template:
      mergePolicy: Replace
      type: Opaque