apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "citynexus"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "citynexus-read"
          serviceAccountRef:
            name: "default"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pull-secret
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: Base64
      key: pull-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: harbor-image-pull
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/dockerconfigjson