apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.serviceName" . }}
  labels: {{- include "frontend.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.nodePort }}
  selector:
    app: {{ .Chart.Name }}
    component: frontend