apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "immerseon.fullname" . }}-citynexus-api
  labels:
    {{- include "immerseon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.citynexus.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: citynexus-api
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: citynexus-api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-citynexus-api
          image: "{{ .Values.citynexus.image.repository }}:{{ .Values.citynexus.image.tag }}"
          ports:
            - containerPort: {{ .Values.citynexus.containerPort }}
          resources:
            {{- toYaml .Values.citynexus.resources | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.mobility.persistence.mountPath }}
              name: mobility-model-api-storage
      volumes:
        - name: mobility-model-api-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ include "mobility-cph.serviceName" . }}-pvc
{{- if .Values.citynexus.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "citynexus.serviceName" . }}-nodeport
  labels:
  {{- include "immerseon.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.citynexus.servicePort }}
      targetPort: {{ .Values.citynexus.containerPort }}
      nodePort: {{ .Values.citynexus.nodePort }}
  selector:
    app: {{ .Chart.Name }}
    component: citynexus-api
{{- end }}