apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "immerseon.fullname" . }}-keycloak
  labels:
    {{- include "immerseon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.keycloak.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: keycloak
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: keycloak
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-keycloak
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          ports:
            - containerPort: {{ .Values.keycloak.containerPort }}
          resources:
            {{- toYaml .Values.keycloak.resources | nindent 12 }}
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloakSecrets.name }}
                  key: {{ .Values.keycloakSecrets.key }}
{{- if .Values.keycloak.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.serviceName" . }}-nodeport
  labels:
  {{- include "immerseon.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.keycloak.servicePort }}
      targetPort: {{ .Values.keycloak.containerPort }}
      nodePort: {{ .Values.keycloak.nodePort }}
  selector:
    app: {{ .Chart.Name }}
    component: keycloak
  type: NodePort
{{- end }}