apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "immerseon.fullname" . }}-{{ include "mobility-svq.serviceName" . }}-pv
spec:
  capacity:
    storage: {{ .Values.mobility.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data