apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ include "mobility-cph.serviceName" . }}-pvc
spec:
  accessModes:
    - {{ .Values.mobility.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.mobility.persistence.size }}