apiVersion: v1
kind: Service
metadata:
  name: {{ include "mobility-api-cph.serviceName" . }}
  labels: {{- include "mobility-api-cph.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.nodePort }}
  selector:
    app: {{ .Chart.Name }}
    component: mobility-model-api-cph