frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: registry-ct.dev.desp.space/citynexus/frontend
    tag: 0.0.55
  containerPort: 80
  servicePort: 8080
  nodePort: 30009
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 2Gi
      cpu: 1000m

mobility:
  replicaCount: 1
  image:
    repository: registry-ct.dev.desp.space/citynexus/mobility-model-api
    tag:
      cph: 0.0.2
      svq: 0.0.5-svq
      aar: 0.0.5-aar
  enabled:
    cph: true
    svq: false
    aar: false
  containerPort: 8000
  servicePort:
    cph: 8001
    svq: 8002
    aar: 8003
  nodePort:
    cph: 30011
    svq: 30012
    aar: 30013
  resources:
    requests:
      memory: 10Gi
      cpu: 6
      nvshare.com/gpu: 1
    limits:
      memory: 20Gi
      cpu: 10
      nvshare.com/gpu: 1
  persistence:
    mountPath: /model_output
    accessMode: ReadWriteOnce
    size: 10Gi

citynexus:
  enabled: true
  replicaCount: 1
  image:
    repository: registry-ct.dev.desp.space/citynexus/backend
    tag: 0.0.12
  containerPort: 8000
  servicePort: 8000
  nodePort: 30007
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 2Gi
      cpu: 1000m

keycloak:
  enabled: true
  replicaCount: 1
  image:
    repository: registry-ct.dev.desp.space/citynexus/keycloak
    tag: 0.0.4
  containerPort: 8080
  servicePort: 8082
  nodePort: 30010
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 10Gi
      cpu: 2000m

flood:
  enabled: false
  replicaCount: 1
  image:
    repository: registry-ct.dev.desp.space/citynexus/flood-model-api
    tag: 0.0.4
  containerPort: 8000
  servicePort: 8083
  nodePort: 30011
  resources:
    limits:
      cpu: "4"
      memory: "8Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"

# For pulling image from Solenix Gitlab to run on Minikube
imagePullSecrets:
  - name: desp-registry-secret
keycloakSecrets:
  name: keycloak-secret
  key: KEYCLOAK_ADMIN_PASSWORD
