image:
  repository: registry-ct.ivv.desp.space/citynexus/frontend
  tag: 0.0.69
  imagePullSecrets:
    - name: harbor-image-pull

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    nginx.ingress.kubernetes.io/auth-secret: "basic-auth-desp"
    nginx.ingress.kubernetes.io/auth-type: "basic"
  hosts:
    - host: citynexus.ivv.desp.space
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: visualization-service
            servicePort: 8080
  tls:
    - hosts:
      - citynexus.ivv.desp.space
      secretName: citynexus-tls
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: desp/service-provider
          operator: In
          values:
            - "citynexus"