apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mobility-api-blq.fullname" . }}
  labels:
    {{- include "mobility-api-blq.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: mobility-model-api-blq
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: mobility-model-api-blq
      annotations:
        elastic.co/dataset: citynexus.monitoring
    spec:
      runtimeClassName : nvidia
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.persistence.mountPath }}
              name: mobility-model-api-blq-storage
      volumes:
        - name: mobility-model-api-blq-storage
          persistentVolumeClaim:
            claimName: citynexus-api-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
