image:
  repository: registry-ct.prod.desp.space/citynexus/mobility-model-api
  tag: "0.0.9-svq"
  imagePullSecrets:
    - name: harbor-image-pull
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: desp/service-provider
          operator: In
          values:
            - "citynexus"