stages:
  - test

sonar_analysis:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  needs: []
  allow_failure: true
  variables:
    SONAR_USER_HOME: ${CI_PROJECT_DIR}/.sonar
    GIT_DEPTH: 0
  cache:
    key: $CI_JOB_NAME
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.token=$SONAR_LOGIN
      -Dsonar.projectKey=SLXENGDE-CITYNEXUS-2023-visualization
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME
      -Dsonar.exclusions=$SONAR_EXCLUSIONS
      -Dsonar.qualitygate.wait=true
