apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "citynexus-api.fullname" . }}
  labels:
    {{- include "citynexus-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: citynexus-api
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: citynexus-api
      annotations:
        elastic.co/dataset: citynexus.monitoring
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.persistence.mountPath }}
              name: citynexus-api-storage
      volumes:
        - name: citynexus-api-storage
          persistentVolumeClaim:
            claimName: {{ include "citynexus-api.name" . }}-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}