apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: citynexus-api-pvc
spec:
  storageClassName: persistent-nfs-storage
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}